name: CI-SelfHosted

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    env:
      DOCKER_REPO: "sumandinda/angulartest"
      BUILD_NUMBER: "${{ github.run_id }}.${{ github.run_number }}"
      BRANCH_NAME: ${{github.branch}}
    runs-on: ["ec2", "self-hosted"]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Run a shell script
        run: "echo Hello, world! This stage will run when branch is main"
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: NPM Build
        run: |
          npm install
          npm run build

      - name: Build Docker
        run: |
          docker build -t "$DOCKER_REPO:$BUILD_NUMBER"  -f Dockerfile .

      - shell: bash
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASS | docker login -u sumandinda --password-stdin
          docker push $DOCKER_REPO:$BUILD_NUMBER
